title: Configuration
data:
  error_404_entry: 059d4d8d-fc60-49f8-8823-7da10549e84e
  copyright_name: 'Berliner Volksbank Immobilien GmbH   | powered by <b><a href=" https://www.inno-brain.de" target="_blank">InnoBrain</a></b>'
  copyright_since: 2024
  privacy_statement_type: none
