tabs:
  main:
    display: Main
    sections:
      -
        display: 'Estate Field List'
        fields:
          -
            handle: estate_field_list
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    new_set:
                      display: 'New Set'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: onoffice_label_id
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'onOffice Label Id'
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                            width: 75
                        -
                          handle: onoffice_label_id_is_active
                          field:
                            default: true
                            type: toggle
                            display: 'onOffice Label Id is Active'
                            icon: toggle
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                            width: 25
              type: replicator
              display: 'Estate Field List'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
      -
        display: 'Filter Options'
        fields:
          -
            handle: filter_options
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    new_set:
                      display: 'New Set'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: onoffice_label_id
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'OnOffice Label Id'
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: filter_enabled_buy_case
                          field:
                            default: true
                            type: toggle
                            display: 'Filter aktiv Kauf'
                            icon: toggle
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                            width: 50
                        -
                          handle: filter_enabled_rent_case
                          field:
                            default: false
                            type: toggle
                            display: 'Filter Aktiv Miete'
                            icon: toggle
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: values_included
                          field:
                            taggable: true
                            push_tags: true
                            multiple: true
                            clearable: false
                            searchable: true
                            cast_booleans: false
                            type: select
                            display: 'Werte einschließen'
                            icon: select
                            instructions: 'Sobald hier Werte definiert werden, sind ausschließlich diese Werte im Filter sichtbar. Die Werte müssen genau mit der Bezeichnung in onOffice übereinstimmen.'
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: values_excluded
                          field:
                            taggable: true
                            push_tags: true
                            multiple: true
                            clearable: false
                            searchable: true
                            cast_booleans: false
                            type: select
                            display: 'Werte ausschließen'
                            icon: select
                            instructions: 'Sobald hier Werte definiert werden, sind diese Werte ausgeschlossen. Alle anderen Werte, die in onOffice konfiguriert sind, werden dann im Filter angezeigt.'
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: label_filter
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'Anzeigename des Filters'
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
              type: replicator
              display: 'Filter Optionen'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
          -
            handle: estate_search_by_radius
            field:
              options:
                'yes': Ja
                'no': Nein
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'Umkreissuche aktiv'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: 'Static Filter Options Reference Estates'
        fields:
          -
            handle: references_filter_options
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                new_set_group:
                  display: 'New Set Group'
                  instructions: null
                  icon: null
                  sets:
                    new_set:
                      display: 'New Set'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: onoffice_label_id
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'OnOffice Label Id'
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: operator
                          field:
                            options:
                              '=': '='
                              '!=': '!='
                              in: in
                              'not in': 'not in'
                              '>=': '>='
                              '>': '>'
                              '<': '<'
                              '<=': '<='
                              like: like
                              between: between
                              'not like': 'not like'
                            taggable: false
                            push_tags: false
                            multiple: false
                            clearable: false
                            searchable: true
                            cast_booleans: false
                            type: select
                            display: 'References Operator'
                            icon: select
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_value_is_active
                          field:
                            default: true
                            type: toggle
                            display: 'References Value is active'
                            icon: toggle
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_value
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'References Value'
                            icon: text
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_range_is_active
                          field:
                            default: false
                            type: toggle
                            display: 'References Range is active'
                            icon: toggle
                            width: 33
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_range_min
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'References Range min'
                            icon: text
                            width: 33
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_range_max
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: 'References Range max'
                            icon: text
                            width: 33
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_in_is_active
                          field:
                            default: false
                            type: toggle
                            display: 'References In is active'
                            icon: toggle
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: references_in_values_as_array
                          field:
                            mode: dynamic
                            type: array
                            display: 'References In Values as Array'
                            icon: array
                            width: 50
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
              type: replicator
              display: 'References Filter Options'
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
      -
        display: 'Static Filter Options Projects'
        fields:
          -
            handle: categories
            field:
              collapse: false
              previews: true
              fullscreen: true
              sets:
                neue_set-gruppe:
                  display: 'Neue Set-Gruppe'
                  instructions: null
                  icon: null
                  sets:
                    neues_set:
                      display: 'Neues Set'
                      instructions: null
                      icon: null
                      fields:
                        -
                          handle: name
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: name
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
                        -
                          handle: onofficelabel
                          field:
                            input_type: text
                            antlers: false
                            type: text
                            display: onOfficeLabel
                            icon: text
                            listable: hidden
                            instructions_position: above
                            visibility: visible
                            hide_display: false
              type: replicator
              display: categories
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
