tabs:
  main:
    display: Hauptteil
    sections:
      -
        fields:
          -
            handle: transparent
            field:
              options:
                'yes': null
                'no': null
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: transparent
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              hide_display: false
